name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - id: release
        name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          manifest-file: .release-please-manifest.json
          config-file: .release-please-config.json

  build-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' && needs.release-please.outputs.tag_name != '' }}
    uses: ./.github/workflows/build-release.yaml
    with:
      tag_name: ${{ needs.release-please.outputs.tag_name }}
    secrets: inherit
